### ISSUE TITLE
Channel pubDate tag missing

### ISSUE THREAD

**Issue by jenkin** [ebergam/halley2RSS#2]
From AlboPOP specs: http://albopop.it/specs/#tag-pubdate

**Comment by ebergam** [comment]
Questo in teoria viene risolto inserendo la data odierna (e si può pensare a qualcosa di meglio), ma non dovrebbe essere missing

**Comment by jenkin** [comment]
Cercalo, a livello di channel non c'è...

**Comment by ebergam** [comment]
aaaaah ma a channel! ahah io come uno scemo che cercavo di capire perché sull'item :D ora risolvo..

**Comment by jenkin** [comment]
Esistono entrambi e hanno due significati diversi... leggi bene le specifiche! :dango:

**Comment by ebergam** [comment]
Ho messo la data di esecuzione come: `datetime.date.today().strftime("%a, %d %b %Y %H:%M:%S %z +0200")` :)

**Comment by jenkin** [comment]
Quel +0200 finale non ci va se c'è %z...
