### ISSUE TITLE
Item act category missing

### ISSUE THREAD

**Issue by jenkin** [ebergam/halley2RSS#3]
From AlboPOP specs: http://albopop.it/specs/#domain-item-act

**Comment by ebergam** [comment]
Occhio, questo link rimanda al category 'uid' `<category domain="http://albopop.it/specs#item-category-uid">2016/15</category>`, che è già implementato

**Comment by ebergam** [comment]
@jenkin da sistemare nelle specs di albopop cc @aborruso

**Comment by jenkin** [comment]
Azz, è l'act ad essere sbagliato, la chiave corretta è item-category-uid (analogo al channel-category-uid)...
