### ISSUE TITLE
Enclosure tags missing

### ISSUE THREAD

**Issue by jenkin** [ebergam/halley2RSS#4]
From AlboPOP specs: http://albopop.it/specs/#tag-enclosure. It's a recommended tag, so it's mandatory if there is an attachment on the original source.

**Comment by ebergam** [comment]
Per questo devo implementare le richieste in un loop diciamo di 'terzo livello', posticipo alla fase in cui implementiamo anche il dowload

**Comment by jenkin** [comment]
Ma io il download lo posso implementare solo se in input ho un url a una risorsa da scaricare... dai dai dai! ;)

**Comment by ebergam** [comment]
@jenkin ci sto lavorando ma ci sto mettendo un po', è un po' più difficile di quanto pensassi

**Comment by jenkin** [comment]
Se hai bisogno di aiuto, pusha una branch a parte e vediamo...

**Comment by ebergam** [comment]
no ok, dovrei aver risolto lo scraping.. Le liste di liste mi han fatto venire un po' di mal di testa ;) comunque gli attributi length e type per ora li lascio stare? Non credo di essere in condizioni di compilarli

**Comment by jenkin** [comment]
Il type sarebbe rilevante, al 99% sarà `application/pdf`... vedi tu, se è complicato, metti a tutti il mimetype del pdf e buonanotte... :)

**Comment by ebergam** [comment]
La seconda che hai detto, poi con calma magari perfezioniamo.. :)

**Comment by ebergam** [comment]
@jenkin Metto anche un length=3000 a tutti che evitiamo problemi di validazione?

**Comment by jenkin** [comment]
Yep!
