### ISSUE TITLE
Title e Description stampano un valore anomalo ripetitivo

### ISSUE THREAD

**Issue by nelsonmau** [ebergam/halley2RSS#6]
è questo ` "> `

allego snap

![albibug](https://cloud.githubusercontent.com/assets/1769578/25011496/d622bc4c-206d-11e7-9b46-dbd6e3957ac4.png)

**Comment by jenkin** [comment]
Se però esiste anche nel documento originale, lo lascerei così com'è...

**Comment by nelsonmau** [comment]
@ebergam a te la palla

**Comment by ebergam** [comment]
@jenkin @nelsonmau Mi sa che è un problema della formattazione XML interna di halley, è il rimasuglio di una chiusura di tag.. Quindi diciamo che in un certo senso è come dici tu ale, ma nell'entry originale a mano non viene fatto ovviamente.. Ad esempio: [l'albo](http://www.comune.montereale.it/c066056/mc/mc_gridev_messi.php?x=&servizio=&bck=http%3A%2F%2Fwww.comune.montereale.it%2Fhh%2Findex.php) di Montereale, e il [relativo feed](http://feeds.ricostruzionetrasparente.it/albi_pretori/Montereale_feed.xml)

**Comment by nelsonmau** [comment]
l'errore sembra essere nel sorgente. Guardate qui

```
<cell>
<a href="#" onClick="visualizza_dettaglio(6580,1);" class="text-overflow-ellipsis""><span class="ellipsis_text">Approvazione preventivo della Ditta Tipolito95 ed assunzione impegno di spesa.</span></a>
</cell>
```

dopo text-overflow-ellipsis è evidente che il tag si chiude male `... psis""><s ...`

**Comment by ebergam** [comment]
@nelsonmau @jenkin quindi che facciamo?

**Comment by jenkin** [comment]
Niente, lascia così...

**Comment by ebergam** [comment]
La funzione per pulire la lascio nel codice senza chiamarla, se cambiamo idea è un attimo
