### ISSUE TITLE
Introdotto l'attributo isPermaLink nel tag guid

### ISSUE THREAD

**Issue by jenkin** [ebergam/halley2RSS#8]
Che non dovrebbe esserci quando il contenuto del tag guid di un item NON è un permalink (anche se dovrebbe esserlo: http://albopop.it/specs/#tag-guid).

**Comment by ebergam** [comment]
Usando il validator w3C succedono cose curiose: se tolgo l'attributo isPermaLink mi dice che deve essere un full url a meno che l'attributo isPermaLink non sia falso.
Se dico isPermaLink falso per tutti mi dice 'unexpected isPermaLink attribute'. Che faccio? :D lo tolgo o lo imposto falso per tutti?

**Comment by jenkin** [comment]
Segui questo: https://www.feedvalidator.org/docs/error/InvalidPermalink.html
